# Generated by Django 4.0.3 on 2022-12-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('gender', models.TextField()),
                ('diamond_quality', models.TextField()),
                ('size', models.TextField()),
                ('weight', models.TextField()),
                ('actual_price', models.TextField()),
                ('selling_price', models.TextField()),
                ('discount', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
