# Generated by Django 4.0.3 on 2022-12-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_product_data_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('gender', models.TextField()),
                ('phone_code', models.TextField()),
                ('phone_no', models.TextField()),
                ('password', models.TextField()),
                ('token', models.TextField()),
            ],
        ),
    ]
