# Generated by Django 4.0.3 on 2022-12-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='dob',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
