# Generated by Django 4.0.3 on 2022-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_user_address_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
    ]
