# Generated by Django 4.0.3 on 2022-12-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_user_whishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('product_id', models.TextField()),
                ('size', models.TextField()),
                ('diamond_quality', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
