# Generated by Django 4.0.3 on 2022-12-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0008_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='quantity',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
