# Generated by Django 4.0.3 on 2022-12-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_user_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='diamond_peice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='diamond_size',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='diamond_wight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='actual_price',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='diamond_quality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='discount',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='gender',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='selling_price',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='size',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='weight',
            field=models.TextField(blank=True),
        ),
    ]
