# Generated by Django 4.0.3 on 2023-01-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0010_product_data_diamond_peice_product_data_diamond_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='diamond_pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond_quality', models.TextField()),
                ('diamond_size', models.TextField()),
                ('diamond_pricing', models.TextField()),
            ],
        ),
    ]
