# Generated by Django 4.0.3 on 2023-01-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0012_metal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='diamond_size',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_cart',
            name='weight',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
