# Generated by Django 4.0.3 on 2023-01-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0013_user_cart_diamond_size_user_cart_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField()),
                ('product_id', models.TextField()),
                ('size', models.TextField()),
                ('weight', models.TextField()),
                ('diamond_quality', models.TextField()),
                ('diamond_size', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=25)),
                ('order_payment_id', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
