# Generated by Django 4.0.3 on 2023-01-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0014_order_details_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='user_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
