# Generated by Django 4.0.3 on 2023-01-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0015_order_payment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='quantity',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
