# Generated by Django 4.0.3 on 2023-01-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0016_order_details_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='diamond',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_details',
            name='gold',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_details',
            name='making_charges',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_details',
            name='platinum',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_details',
            name='shipping',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_details',
            name='tax',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
