# Generated by Django 4.0.3 on 2023-01-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0017_order_details_diamond_order_details_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='order_status',
            field=models.TextField(choices=[('p', 'p'), ('c', 'c'), ('d', 'd'), ('o', 'o')], default='p', max_length=1),
        ),
    ]
