# Generated by Django 4.0.3 on 2023-01-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0021_alter_product_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='password',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='token',
            field=models.TextField(blank=True),
        ),
    ]
