# Generated by Django 4.0.3 on 2023-01-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0022_alter_user_data_password_alter_user_data_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='admin_placed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
