# Generated by Django 4.0.3 on 2023-01-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0023_order_payment_admin_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='dob',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='gender',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='phone_code',
            field=models.TextField(blank=True),
        ),
    ]
