# Generated by Django 4.0.3 on 2023-01-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0024_alter_user_data_dob_alter_user_data_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
