# Generated by Django 4.0.3 on 2023-02-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0026_order_payment_admin_accept_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_data',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='product_data',
            name='selling_price',
        ),
    ]
