# Generated by Django 4.0.3 on 2023-03-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0027_remove_product_data_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_data',
            name='diamond_peice',
        ),
    ]
