# Generated by Django 4.0.3 on 2023-03-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0028_remove_product_data_diamond_peice'),
    ]

    operations = [
        migrations.CreateModel(
            name='no_login_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user_cart',
            name='no_user_id',
            field=models.TextField(blank=True),
        ),
    ]
