# Generated by Django 4.0.3 on 2023-03-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0029_no_login_user_user_cart_no_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='user_type',
            field=models.TextField(default='u'),
        ),
    ]
